sonar.projectKey=bc-white_Infrastructure-As-Code
sonar.organization=bc-white
sonar.projectName=Infrastructure-As-Code
sonar.projectVersion=0.0.6
sonar.sources=scripts/python,code/c/src
# Exclude test directories from analysis and coverage
sonar.exclusions=**/tests/**,**/*test*,**/*Test*
# Sonar Python versions
sonar.python.version=3.12
