import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '../components/ui/button';
import { ArrowLeft, Shield, AlertTriangle, FileText } from 'lucide-react';

const Terms = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
        {/* Header */}
        <div className="mb-8">
          <Button
            variant="ghost"
            onClick={() => navigate(-1)}
            className="mb-6 text-gray-600 hover:text-gray-900"
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back
          </Button>
          
          <div className="flex items-center space-x-3 mb-4">
            <div className="p-2 bg-[#075b7d]/10 rounded-lg">
              <FileText className="w-6 h-6 text-[#075b7d]" />
            </div>
            <div>
              <h1 className="text-3xl font-bold text-gray-900">Terms of Service</h1>
              <p className="text-gray-600">Last updated: January 15, 2025</p>
            </div>
          </div>
        </div>

        {/* Content */}
        <div className="prose prose-gray max-w-none">
          {/* Important Notice */}
          <div className="bg-amber-50 border border-amber-200 rounded-lg p-6 mb-8">
            <div className="flex items-start space-x-3">
              <AlertTriangle className="w-6 h-6 text-amber-600 mt-1 flex-shrink-0" />
              <div>
                <h3 className="text-lg font-semibold text-amber-900 mb-2">Important Notice</h3>
                <p className="text-amber-800 text-sm leading-relaxed">
                  MockSurvey365 is a simulation and training tool. The reports generated by this platform are for educational and preparation purposes only and should not be used for actual regulatory compliance or submitted to CMS or other regulatory bodies.
                </p>
              </div>
            </div>
          </div>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">1. Acceptance of Terms</h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              By accessing or using MockSurvey365 ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of these terms, you may not access the Service.
            </p>
            <p className="text-gray-700 leading-relaxed">
              These Terms apply to all visitors, users, and others who access or use the Service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">2. Description of Service</h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              MockSurvey365 is a healthcare compliance training platform that provides:
            </p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2 mb-4">
              <li>CMS-style nursing home survey simulation tools</li>
              <li>Deficiency statement generation and training</li>
              <li>Educational resources and compliance materials</li>
              <li>Report generation for training purposes</li>
              <li>F-tag reference database and search functionality</li>
            </ul>
            <p className="text-gray-700 leading-relaxed">
              <strong>The Service is for educational and training purposes only. Generated reports are mock documents and should not be used for actual regulatory submissions.</strong>
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">3. User Accounts</h2>
            <h3 className="text-lg font-semibold text-gray-900 mb-3">3.1 Account Creation</h3>
            <p className="text-gray-700 leading-relaxed mb-4">
              To access certain features, you must create an account. You agree to provide accurate, current, and complete information during registration and to update such information as necessary.
            </p>
            
            <h3 className="text-lg font-semibold text-gray-900 mb-3">3.2 Account Security</h3>
            <p className="text-gray-700 leading-relaxed mb-4">
              You are responsible for safeguarding your password and all activities under your account. You must notify us immediately of any unauthorized use of your account.
            </p>
            
            <h3 className="text-lg font-semibold text-gray-900 mb-3">3.3 Account Types</h3>
            <ul className="list-disc pl-6 text-gray-700 space-y-2">
              <li><strong>Demo Accounts:</strong> Limited access with watermarked outputs</li>
              <li><strong>Professional Accounts:</strong> Full access to core features</li>
              <li><strong>Consultant Licenses:</strong> Multi-facility management capabilities</li>
              <li><strong>Pay-Per-Report:</strong> Single-use report generation</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">4. Subscription and Billing</h2>
            <h3 className="text-lg font-semibold text-gray-900 mb-3">4.1 Subscription Plans</h3>
            <p className="text-gray-700 leading-relaxed mb-4">
              We offer various subscription plans with different features and limitations. Current pricing and features are available on our pricing page.
            </p>
            
            <h3 className="text-lg font-semibold text-gray-900 mb-3">4.2 Billing</h3>
            <ul className="list-disc pl-6 text-gray-700 space-y-2 mb-4">
              <li>Subscription fees are charged in advance on a monthly or annual basis</li>
              <li>Payment is due immediately upon subscription activation</li>
              <li>We use Stripe for secure payment processing</li>
              <li>All fees are non-refundable except as required by law or as specified in our refund policy</li>
            </ul>
            
            <h3 className="text-lg font-semibold text-gray-900 mb-3">4.3 Free Trials</h3>
            <p className="text-gray-700 leading-relaxed mb-4">
              Some plans include a free trial period. You will not be charged during the trial period. At the end of the trial, your subscription will automatically renew unless you cancel.
            </p>
            
            <h3 className="text-lg font-semibold text-gray-900 mb-3">4.4 Cancellation</h3>
            <p className="text-gray-700 leading-relaxed">
              You may cancel your subscription at any time. Cancellation takes effect at the end of your current billing period. You will retain access to paid features until the end of your billing period.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">5. Acceptable Use</h2>
            <p className="text-gray-700 leading-relaxed mb-4">You agree not to:</p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2 mb-4">
              <li>Use the Service for any unlawful purpose or in violation of any local, state, national, or international law</li>
              <li>Submit mock reports generated by our Service to CMS or other regulatory bodies</li>
              <li>Share your account credentials with others</li>
              <li>Attempt to gain unauthorized access to the Service or its related systems</li>
              <li>Use the Service to harass, abuse, or harm another person</li>
              <li>Reverse engineer, decompile, or disassemble any part of the Service</li>
              <li>Remove or alter any proprietary notices on the Service</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">6. Intellectual Property</h2>
            <h3 className="text-lg font-semibold text-gray-900 mb-3">6.1 Our Content</h3>
            <p className="text-gray-700 leading-relaxed mb-4">
              The Service and its original content, features, and functionality are owned by MockSurvey365 and are protected by international copyright, trademark, patent, trade secret, and other intellectual property laws.
            </p>
            
            <h3 className="text-lg font-semibold text-gray-900 mb-3">6.2 User Content</h3>
            <p className="text-gray-700 leading-relaxed mb-4">
              You retain ownership of content you create using the Service. By using the Service, you grant us a limited license to store, process, and display your content as necessary to provide the Service.
            </p>
            
            <h3 className="text-lg font-semibold text-gray-900 mb-3">6.3 CMS Content</h3>
            <p className="text-gray-700 leading-relaxed">
              F-tag information and regulatory guidance are based on publicly available CMS materials. We do not claim ownership of CMS content and regulations.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">7. Privacy and Data Protection</h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              Your privacy is important to us. Our Privacy Policy explains how we collect, use, and protect your information when you use our Service.
            </p>
            <p className="text-gray-700 leading-relaxed">
              We implement appropriate security measures to protect your personal information and comply with applicable data protection laws, including HIPAA where applicable.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">8. Disclaimers</h2>
            <div className="bg-red-50 border border-red-200 rounded-lg p-6 mb-4">
              <div className="flex items-start space-x-3">
                <Shield className="w-6 h-6 text-red-600 mt-1 flex-shrink-0" />
                <div>
                  <h3 className="text-lg font-semibold text-red-900 mb-2">Important Disclaimer</h3>
                  <p className="text-red-800 text-sm leading-relaxed">
                    THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DO NOT GUARANTEE THAT THE SIMULATED SURVEYS OR REPORTS ACCURATELY REFLECT ACTUAL CMS SURVEY PROCESSES OR REQUIREMENTS.
                  </p>
                </div>
              </div>
            </div>
            
            <p className="text-gray-700 leading-relaxed mb-4">
              MockSurvey365 is a training tool and should not be relied upon as:
            </p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2">
              <li>Legal advice or regulatory guidance</li>
              <li>A substitute for professional healthcare compliance consulting</li>
              <li>An accurate representation of actual CMS survey processes</li>
              <li>A guarantee of survey preparedness or compliance</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">9. Limitation of Liability</h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              IN NO EVENT SHALL MOCKSURVEY365 BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE damages, INCLUDING WITHOUT LIMITATION LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES.
            </p>
            <p className="text-gray-700 leading-relaxed">
              OUR TOTAL LIABILITY FOR ANY CLAIMS ARISING FROM YOUR USE OF THE SERVICE SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE TWELVE MONTHS PRECEDING THE CLAIM.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">10. Termination</h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              We may terminate or suspend your account and access to the Service immediately, without prior notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties.
            </p>
            <p className="text-gray-700 leading-relaxed">
              Upon termination, your right to use the Service will cease immediately, but provisions that by their nature should survive termination will remain in effect.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">11. Changes to Terms</h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              We reserve the right to modify these Terms at any time. We will notify users of material changes via email or through the Service.
            </p>
            <p className="text-gray-700 leading-relaxed">
              Your continued use of the Service after changes become effective constitutes acceptance of the new Terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">12. Contact Information</h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              If you have any questions about these Terms, please contact us:
            </p>
            <div className="bg-gray-50 rounded-lg p-4">
              <p className="text-gray-700"><strong>MockSurvey365 Support</strong></p>
              <p className="text-gray-700">Email: staff@theinspac.com</p>
              <p className="text-gray-700">Phone: 1-800-SURVEY-365</p>
              <p className="text-gray-700">Address: 123 Healthcare Blvd, Suite 456, Medical City, HC 12345</p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">13. Governing Law</h2>
            <p className="text-gray-700 leading-relaxed">
              These Terms shall be governed by and construed in accordance with the laws of the State of California, without regard to its conflict of law provisions. Any disputes arising from these Terms or your use of the Service shall be resolved in the courts of California.
            </p>
          </section>
        </div>

        {/* Footer */}
        <div className="mt-12 pt-8 border-t border-gray-200">
          <p className="text-sm text-gray-500 text-center">
            By using MockSurvey365, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
          </p>
        </div>
      </div>
    </div>
  );
};

export default Terms; 