# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "staging" ]

jobs:
  build:

    runs-on: ["self-hosted","mocksurveyapistagingv1"]

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
      with:
        # Preserve existing files that aren't in git
        clean: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Create .env file
      run: |
        echo "PORT=${{ secrets.PORT }}" > .env
        echo "ENV=${{ secrets.ENV }}" >> .env
        echo "HEALTH=${{ secrets.HEALTH }}" >> .env
        echo "VERSION=${{ secrets.VERSION }}" >> .env
        echo "DB=${{ secrets.DB_STAGING }}" >> .env
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
        echo "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}" >> .env
        echo "AWS_SECRET_KEY_ID=${{ secrets.AWS_SECRET_KEY_ID }}" >> .env
        echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "API_BASE_URL=${{ secrets.API_BASE_URL_STAGING }}" >> .env
        echo "CP_URL=${{ secrets.CP_URL_STAGING }}" >> .env
        echo "SITE_LOGIN_URL=${{ secrets.SITE_LOGIN_URL_STAGING }}" >> .env
        echo "EMAIL_API_KEY=${{ secrets.EMAIL_API_KEY }}" >> .env
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
        echo "GAMMA_API_KEY=${{ secrets.GAMMA_API_KEY }}" >> .env
        echo "TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}" >> .env
        echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
        echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env
        echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env
        echo "REDIS_DB=${{ secrets.REDIS_DB }}" >> .env
        
    - name: Backup public directory
      run: |
        if [ -d "public" ]; then
          echo "Backing up public directory..."
          cp -r public public_backup
        fi
    - run: npm install --legacy-peer-deps
    - run: npm run build --if-present
    - run: npx pm2 restart staging --update-env
