const mongoose = require("mongoose");
const FacilitySchema = new mongoose.Schema(
  {
    name: { type: String, default: "" },
    type: { type: mongoose.Schema.Types.ObjectId, ref: "FacilityTypes" },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    uniqueOrgCode: { type: String, default: "" },
    address: {
      street: { type: String, default: "" },
      city: { type: String, default: "" },
      state: { type: String, default: "" },
      zipCode: { type: String, default: "" },
      country: { type: String, default: "" },
    },

    size: {
      beds: { type: Number, default: 0 },
      floors: { type: Number, default: 0 },
    },
    contact: { type: Array, default: [] },
    secondaryContactPhone: { type: String, default: "" },
    notes: { type: String, default: "" },
    lastSurvey: { type: Date, default: "" },
    providerNumber: { type: String, default: "" },

    CMS_Certification_Number_CCN: { type: String, default: "" },
    Provider_Name: { type: String, default: "" },
    Provider_Address: { type: String, default: "" },
    City_Town: { type: String, default: "" },
    State: { type: String, default: "" },
    ZIP_Code: { type: String, default: "" },
    Telephone_Number: { type: String, default: "" },
    Provider_SSA_County_Code: { type: String, default: "" },
    County_Parish: { type: String, default: "" },
    Ownership_Type: { type: String, default: "" },
    Number_of_Certified_Beds: { type: String, default: "" },
    Average_Number_of_Residents_per_Day: { type: String, default: "" },
    Average_Number_of_Residents_per_Day_Footnote: { type: String, default: "" },
    Provider_Type: { type: String, default: "" },
    Provider_Resides_in_Hospital: { type: String, default: "" },
    Legal_Business_Name: { type: String, default: "" },
    Date_First_Approved_to_Provide_Medicare_and_Medicaid_Services: {
      type: String,
      default: "",
    },
    Chain_Name: { type: String, default: "" },
    Chain_ID: { type: String, default: "" },
    Number_of_Facilities_in_Chain: { type: String, default: "" },
    Chain_Average_Overall_5_star_Rating: { type: String, default: "" },
    Chain_Average_Health_Inspection_Rating: { type: String, default: "" },
    Chain_Average_Staffing_Rating: { type: String, default: "" },
    Chain_Average_QM_Rating: { type: String, default: "" },
    Continuing_Care_Retirement_Community: { type: String, default: "" },
    Special_Focus_Status: { type: String, default: "" },
    Abuse_Icon: { type: String, default: "" },
    Most_Recent_Health_Inspection_More_Than_2_Years_Ago: {
      type: String,
      default: "",
    },
    Provider_Changed_Ownership_in_Last_12_Months: { type: String, default: "" },
    With_a_Resident_and_Family_Council: { type: String, default: "" },
    Automatic_Sprinkler_Systems_in_All_Required_Areas: {
      type: String,
      default: "",
    },
    Overall_Rating: { type: String, default: "" },
    Overall_Rating_Footnote: { type: String, default: "" },
    Health_Inspection_Rating: { type: String, default: "" },
    Health_Inspection_Rating_Footnote: { type: String, default: "" },
    QM_Rating: { type: String, default: "" },
    QM_Rating_Footnote: { type: String, default: "" },
    Long_Stay_QM_Rating: { type: String, default: "" },
    Long_Stay_QM_Rating_Footnote: { type: String, default: "" },
    Short_Stay_QM_Rating: { type: String, default: "" },
    Short_Stay_QM_Rating_Footnote: { type: String, default: "" },
    Staffing_Rating: { type: String, default: "" },
    Staffing_Rating_Footnote: { type: String, default: "" },
    Reported_Staffing_Footnote: { type: String, default: "" },
    Physical_Therapist_Staffing_Footnote: { type: String, default: "" },
    Reported_Nurse_Aide_Staffing_Hours_per_Resident_per_Day: {
      type: String,
      default: "",
    },
    Reported_LPN_Staffing_Hours_per_Resident_per_Day: {
      type: String,
      default: "",
    },
    Reported_RN_Staffing_Hours_per_Resident_per_Day: {
      type: String,
      default: "",
    },
    Reported_Licensed_Staffing_Hours_per_Resident_per_Day: {
      type: String,
      default: "",
    },
    Reported_Total_Nurse_Staffing_Hours_per_Resident_per_Day: {
      type: String,
      default: "",
    },
    Total_number_of_nurse_staff_hours_per_resident_per_day_on_the_weekend: {
      type: String,
      default: "",
    },
    Registered_Nurse_hours_per_resident_per_day_on_the_weekend: {
      type: String,
      default: "",
    },
    Reported_Physical_Therapist_Staffing_Hours_per_Resident_Per_Day: {
      type: String,
      default: "",
    },
    Total_nursing_staff_turnover: { type: String, default: "" },
    Total_nursing_staff_turnover_footnote: { type: String, default: "" },
    Registered_Nurse_turnover: { type: String, default: "" },
    Registered_Nurse_turnover_footnote: { type: String, default: "" },
    Number_of_administrators_who_have_left_the_nursing_home: {
      type: String,
      default: "",
    },
    Administrator_turnover_footnote: { type: String, default: "" },
    Nursing_Case_Mix_Index: { type: String, default: "" },
    Nursing_Case_Mix_Index_Ratio: { type: String, default: "" },
    Case_Mix_Nurse_Aide_Staffing_Hours_per_Resident_per_Day: {
      type: String,
      default: "",
    },
    Case_Mix_LPN_Staffing_Hours_per_Resident_per_Day: {
      type: String,
      default: "",
    },
    Case_Mix_RN_Staffing_Hours_per_Resident_per_Day: {
      type: String,
      default: "",
    },
    Case_Mix_Total_Nurse_Staffing_Hours_per_Resident_per_Day: {
      type: String,
      default: "",
    },
    Case_Mix_Weekend_Total_Nurse_Staffing_Hours_per_Resident_per_Day: {
      type: String,
      default: "",
    },
    Adjusted_Nurse_Aide_Staffing_Hours_per_Resident_per_Day: {
      type: String,
      default: "",
    },
    Adjusted_LPN_Staffing_Hours_per_Resident_per_Day: {
      type: String,
      default: "",
    },
    Adjusted_RN_Staffing_Hours_per_Resident_per_Day: {
      type: String,
      default: "",
    },
    Adjusted_Total_Nurse_Staffing_Hours_per_Resident_per_Day: {
      type: String,
      default: "",
    },
    Adjusted_Weekend_Total_Nurse_Staffing_Hours_per_Resident_per_Day: {
      type: String,
      default: "",
    },
    Rating_Cycle_1_Standard_Survey_Health_Date: { type: String, default: "" },
    Rating_Cycle_1_Total_Number_of_Health_Deficiencies: {
      type: String,
      default: "",
    },
    Rating_Cycle_1_Number_of_Standard_Health_Deficiencies: {
      type: String,
      default: "",
    },
    Rating_Cycle_1_Number_of_Complaint_Health_Deficiencies: {
      type: String,
      default: "",
    },
    Rating_Cycle_1_Health_Deficiency_Score: { type: String, default: "" },
    Rating_Cycle_1_Number_of_Health_Revisits: { type: String, default: "" },
    Rating_Cycle_1_Health_Revisit_Score: { type: String, default: "" },
    Rating_Cycle_1_Total_Health_Score: { type: String, default: "" },
    Rating_Cycle_2_Standard_Health_Survey_Date: { type: String, default: "" },
    Rating_Cycle_2_3_Total_Number_of_Health_Deficiencies: {
      type: String,
      default: "",
    },
    Rating_Cycle_2_Number_of_Standard_Health_Deficiencies: {
      type: String,
      default: "",
    },
    Rating_Cycle_2_3_Number_of_Complaint_Health_Deficiencies: {
      type: String,
      default: "",
    },
    Rating_Cycle_2_3_Health_Deficiency_Score: { type: String, default: "" },
    Rating_Cycle_2_Number_of_Health_Revisits: { type: String, default: "" },
    Rating_Cycle_2_3_Number_of_Health_Revisits: { type: String, default: "" },
    Rating_Cycle_2_3_Health_Revisit_Score: { type: String, default: "" },
    Rating_Cycle_2_3_Total_Health_Score: { type: String, default: "" },
    Total_Weighted_Health_Survey_Score: { type: String, default: "" },
    Number_of_Facility_Reported_Incidents: { type: String, default: "" },
    Number_of_Substantiated_Complaints: { type: String, default: "" },
    Number_of_Citations_from_Infection_Control_Inspections: {
      type: String,
      default: "",
    },
    Number_of_Fines: { type: String, default: "" },
    Total_Amount_of_Fines_in_Dollars: { type: String, default: "" },
    Number_of_Payment_Denials: { type: String, default: "" },
    Total_Number_of_Penalties: { type: String, default: "" },
    Location: { type: String, default: "" },
    Latitude: { type: String, default: "" },
    Longitude: { type: String, default: "" },
    Geocoding_Footnote: { type: String, default: "" },
    Processing_Date: { type: String, default: "" },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model("Facility", FacilitySchema);
