const mongoose = require("mongoose");

const nursingHomeProviderSchema = new mongoose.Schema(
  {
    CMS_Certification_Number_CCN: { type: String },
    Provider_Name: { type: String },
    Provider_Address: { type: String },
    City_Town: { type: String },
    State: { type: String },
    ZIP_Code: { type: String },
    Telephone_Number: { type: String },
    Provider_SSA_County_Code: { type: String },
    County_Parish: { type: String },
    Ownership_Type: { type: String },
    Number_of_Certified_Beds: { type: String },
    Average_Number_of_Residents_per_Day: { type: String },
    Average_Number_of_Residents_per_Day_Footnote: { type: String },
    Provider_Type: { type: String },
    Provider_Resides_in_Hospital: { type: String },
    Legal_Business_Name: { type: String },
    Date_First_Approved_to_Provide_Medicare_and_Medicaid_Services: { type: String },
    Chain_Name: { type: String },
    Chain_ID: { type: String },
    Number_of_Facilities_in_Chain: { type: String },
    Chain_Average_Overall_5_star_Rating: { type: String },
    Chain_Average_Health_Inspection_Rating: { type: String },
    Chain_Average_Staffing_Rating: { type: String },
    Chain_Average_QM_Rating: { type: String },
    Continuing_Care_Retirement_Community: { type: String },
    Special_Focus_Status: { type: String },
    Abuse_Icon: { type: String },
    Most_Recent_Health_Inspection_More_Than_2_Years_Ago: { type: String },
    Provider_Changed_Ownership_in_Last_12_Months: { type: String },
    With_a_Resident_and_Family_Council: { type: String },
    Automatic_Sprinkler_Systems_in_All_Required_Areas: { type: String },
    Overall_Rating: { type: String },
    Overall_Rating_Footnote: { type: String },
    Health_Inspection_Rating: { type: String },
    Health_Inspection_Rating_Footnote: { type: String },
    QM_Rating: { type: String },
    QM_Rating_Footnote: { type: String },
    Long_Stay_QM_Rating: { type: String },
    Long_Stay_QM_Rating_Footnote: { type: String },
    Short_Stay_QM_Rating: { type: String },
    Short_Stay_QM_Rating_Footnote: { type: String },
    Staffing_Rating: { type: String },
    Staffing_Rating_Footnote: { type: String },
    Reported_Staffing_Footnote: { type: String },
    Physical_Therapist_Staffing_Footnote: { type: String },
    Reported_Nurse_Aide_Staffing_Hours_per_Resident_per_Day: { type: String },
    Reported_LPN_Staffing_Hours_per_Resident_per_Day: { type: String },
    Reported_RN_Staffing_Hours_per_Resident_per_Day: { type: String },
    Reported_Licensed_Staffing_Hours_per_Resident_per_Day: { type: String },
    Reported_Total_Nurse_Staffing_Hours_per_Resident_per_Day: { type: String },
    Total_number_of_nurse_staff_hours_per_resident_per_day_on_the_weekend: { type: String },
    Registered_Nurse_hours_per_resident_per_day_on_the_weekend: { type: String },
    Reported_Physical_Therapist_Staffing_Hours_per_Resident_Per_Day: { type: String },
    Total_nursing_staff_turnover: { type: String },
    Total_nursing_staff_turnover_footnote: { type: String },
    Registered_Nurse_turnover: { type: String },
    Registered_Nurse_turnover_footnote: { type: String },
    Number_of_administrators_who_have_left_the_nursing_home: { type: String },
    Administrator_turnover_footnote: { type: String },
    Nursing_Case_Mix_Index: { type: String },
    Nursing_Case_Mix_Index_Ratio: { type: String },
    Case_Mix_Nurse_Aide_Staffing_Hours_per_Resident_per_Day: { type: String },
    Case_Mix_LPN_Staffing_Hours_per_Resident_per_Day: { type: String },
    Case_Mix_RN_Staffing_Hours_per_Resident_per_Day: { type: String },
    Case_Mix_Total_Nurse_Staffing_Hours_per_Resident_per_Day: { type: String },
    Case_Mix_Weekend_Total_Nurse_Staffing_Hours_per_Resident_per_Day: { type: String },
    Adjusted_Nurse_Aide_Staffing_Hours_per_Resident_per_Day: { type: String },
    Adjusted_LPN_Staffing_Hours_per_Resident_per_Day: { type: String },
    Adjusted_RN_Staffing_Hours_per_Resident_per_Day: { type: String },
    Adjusted_Total_Nurse_Staffing_Hours_per_Resident_per_Day: { type: String },
    Adjusted_Weekend_Total_Nurse_Staffing_Hours_per_Resident_per_Day: { type: String },
    Rating_Cycle_1_Standard_Survey_Health_Date: { type: String },
    Rating_Cycle_1_Total_Number_of_Health_Deficiencies: { type: String },
    Rating_Cycle_1_Number_of_Standard_Health_Deficiencies: { type: String },
    Rating_Cycle_1_Number_of_Complaint_Health_Deficiencies: { type: String },
    Rating_Cycle_1_Health_Deficiency_Score: { type: String },
    Rating_Cycle_1_Number_of_Health_Revisits: { type: String },
    Rating_Cycle_1_Health_Revisit_Score: { type: String },
    Rating_Cycle_1_Total_Health_Score: { type: String },
    Rating_Cycle_2_Standard_Health_Survey_Date: { type: String },
    Rating_Cycle_2_3_Total_Number_of_Health_Deficiencies: { type: String },
    Rating_Cycle_2_Number_of_Standard_Health_Deficiencies: { type: String },
    Rating_Cycle_2_3_Number_of_Complaint_Health_Deficiencies: { type: String },
    Rating_Cycle_2_3_Health_Deficiency_Score: { type: String },
    Rating_Cycle_2_3_Number_of_Health_Revisits: { type: String },
    Rating_Cycle_2_3_Health_Revisit_Score: { type: String },
    Rating_Cycle_2_3_Total_Health_Score: { type: String },
    Total_Weighted_Health_Survey_Score: { type: String },
    Number_of_Facility_Reported_Incidents: { type: String },
    Number_of_Substantiated_Complaints: { type: String },
    Number_of_Citations_from_Infection_Control_Inspections: { type: String },
    Number_of_Fines: { type: String },
    Total_Amount_of_Fines_in_Dollars: { type: String },
    Number_of_Payment_Denials: { type: String },
    Total_Number_of_Penalties: { type: String },
    Location: { type: String },
    Latitude: { type: String },
    Longitude: { type: String },
    Geocoding_Footnote: { type: String },
    Processing_Date: { type: String },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model("nursingHomeProviders", nursingHomeProviderSchema);
