const mongoose = require("mongoose");

const NursingHomeSchema = new mongoose.Schema(
  {
    Chain: { type: String},
    Chain_ID: { type: String, default: "" },
    Number_of_facilities: { type: String, default: "" },
    Number_of_states_and_territories_with_operations: { type: String, default: "" },
    Number_of_Special_Focus_Facilities_SFF: { type: String, default: "" },
    Number_of_SFF_candidates: { type: String, default: "" },
    Number_of_facilities_with_an_abuse_icon: { type: String, default: "" },
    Percentage_of_facilities_with_an_abuse_icon: { type: String, default: "" },
    Percent_of_facilities_classified_as_for_profit: { type: String, default: "" },
    Percent_of_facilities_classified_as_non_profit: { type: String, default: "" },
    Percent_of_facilities_classified_as_government_owned: { type: String, default: "" },
    Average_overall_5_star_rating: { type: String, default: "" },
    Average_health_inspection_rating: { type: String, default: "" },
    Average_staffing_rating: { type: String, default: "" },
    Average_quality_rating: { type: String, default: "" },
    Average_total_nurse_hours_per_resident_day: { type: String, default: "" },
    Average_total_weekend_nurse_hours_per_resident_day: { type: String, default: "" },
    Average_total_registered_nurse_hours_per_resident_day: { type: String, default: "" },
    Average_total_Registered_Nurse_hours_per_resident_day: { type: String, default: "" },
    Average_total_nursing_staff_turnover_percentage: { type: String, default: "" },
    Average_registered_nurse_turnover_percentage: { type: String, default: "" },
    Average_number_of_administrators_who_have_left_the_nursing_home: { type: String, default: "" },
    Total_number_of_fines: { type: String, default: "" },
    Average_number_of_fines: { type: String, default: "" },
    Total_amount_of_fines_in_dollars: { type: String, default: "" },
    Average_amount_of_fines_in_dollars: { type: String, default: "" },
    Total_number_of_payment_denials: { type: String, default: "" },
    Average_number_of_payment_denials: { type: String, default: "" },
    Average_percentage_of_short_stay_residents_who_were_re_hospitalized_after_a_nursing_home_admission: { type: String, default: "" },
    Average_percentage_of_short_stay_residents_who_have_had_an_outpatient_emergency_department_visit: { type: String, default: "" },
    Average_percentage_of_short_stay_residents_who_newly_received_an_antipsychotic_medication: { type: String, default: "" },
    Average_percentage_of_short_stay_residents_with_pressure_ulcers_or_pressure_injuries_that_are_new_or_worsened: { type: String, default: "" },
    Average_percentage_of_short_stay_residents_who_are_at_or_above_an_expected_ability_to_care_for_themselves_and_move_around_at_discharge: { type: String, default: "" },
    Average_percentage_of_short_stay_residents_who_were_assessed_and_appropriately_given_the_seasonal_influenza_vaccine: { type: String, default: "" },
    Average_percentage_of_short_stay_residents_who_were_assessed_and_appropriately_given_the_pneumococcal_vaccine: { type: String, default: "" },
    Average_number_of_hospitalizations_per_1000_long_stay_resident_days: { type: String, default: "" },
    Average_number_of_outpatient_emergency_department_visits_per_1000_long_stay_resident_days: { type: String, default: "" },
    Average_percentage_of_long_stay_residents_who_received_an_antipsychotic_medication: { type: String, default: "" },
    Average_percentage_of_long_stay_residents_experiencing_one_or_more_falls_with_major_injury: { type: String, default: "" },
    Average_percentage_of_long_stay_residents_with_pressure_ulcers: { type: String, default: "" },
    Average_percentage_of_long_stay_residents_with_a_urinary_tract_infection: { type: String, default: "" },
    Average_percentage_of_long_stay_residents_who_have_or_had_a_catheter_inserted_and_left_in_their_bladder: { type: String, default: "" },
    Average_percentage_of_long_stay_residents_whose_ability_to_move_independently_worsened: { type: String, default: "" },
    Average_percentage_of_long_stay_residents_whose_need_for_help_with_activities_of_daily_living_has_increased: { type: String, default: "" },
    Average_percentage_of_long_stay_residents_who_were_assessed_and_appropriately_given_the_seasonal_influenza_vaccine: { type: String, default: "" },
    Average_percentage_of_long_stay_residents_who_were_assessed_and_appropriately_given_the_pneumococcal_vaccine: { type: String, default: "" },
    Average_percentage_of_long_stay_residents_who_were_physically_restrained: { type: String, default: "" },
    Average_percentage_of_long_stay_residents_with_new_or_worsened_bowel_or_bladder_incontinence: { type: String, default: "" },
    Average_percentage_of_long_stay_residents_who_lose_too_much_weight: { type: String, default: "" },
    Average_percentage_of_long_stay_residents_who_have_symptoms_of_depression: { type: String, default: "" },
    Average_percentage_of_long_stay_residents_who_used_antianxiety_or_hypnotic_medication: { type: String, default: "" },
    Average_rate_of_potentially_preventable_hospital_readmissions_30_days_after_discharge_from_a_snf: { type: String, default: "" },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true
    }
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model("nursing_homes", NursingHomeSchema);