name: Dev Build
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - development
  push:
    branches:
      - development
jobs:
  SonarCloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: SonarCloudScan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
